const HOST = 'http://192.168.2.13/DACN1_API/api';
export default {
    URL_addNewProduct: HOST + '/addNewProduct.php',
    URL_deleteCart: HOST + '/deleteCart.php',
    URL_getCart: HOST + '/getCart.php',
    URL_getCategory: HOST + '/getCategory.php',
    URL_getHomeAdmin: HOST + '/getHomeAdmin.php',
    URL_getIdAdmin: HOST + '/getIdAdmin.php',
    URL_getInformation: HOST + '/getInformation.php',
    URL_getNewProduct: HOST + '/getNewProduct.php',
    URL_getOrder: HOST + '/getOrder.php',
    URL_getProduct: HOST + '/getProduct.php',
    URL_getProductCategory: HOST + '/getProductCategory.php',
    URL_getProductDetail: HOST + '/getProductDetail.php',
    URL_getProductRelated: HOST + '/getProductRelated.php',
    URL_getProductWithCate: HOST + '/getProductWithCate.php',
    URL_getTopProduct: HOST + '/getTopProduct.php',
    URL_getUser: HOST + '/getUser.php',
    URL_searchProduct: HOST + '/searchProduct.php',
    URL_setCart: HOST + '/setCart.php',
    URL_setInfor: HOST + '/setInfor.php',
    URL_setNewPass: HOST + '/setNewPass.php',
    URL_setNewUser: HOST + '/setNewUser.php',
    URL_setOrder: HOST + '/setOrder.php',
    URL_setViewProduct: HOST + '/setViewProduct.php',
    URL_updateCart: HOST + '/updateCart.php',
    URL_deleteProduct: HOST + '/deleteProduct.php'
};